version: 1
builds:
  - id: hxtp-cli
    main: ./cmd/hxtp-cli
    binary: hxtp-cli
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}
